name: Tag, Release, and Docker Image

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: write
    packages: write

jobs:
    build_version:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Set up JDK
            uses: actions/setup-java@v2
            with:
              distribution: 'adopt'
              java-version: '11'
              
          - name: Extract version from pom.xml
            id: extract_version
            run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    
        outputs:
            version: ${{ env.VERSION }}
        
    tag_and_release:
        needs: build_version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Create Tag
              id: create_tag
              run: |
                git config --global user.name 'github-actions'
                git config --global user.email 'github-actions@github.com'
                git tag ${{ needs.build_version.outputs.version }}
                git push origin ${{ needs.build_version.outputs.version }}
                
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ needs.build_version.outputs.version }}
                release_name: ${{ needs.build_version.outputs.version }}
                draft: false
                prerelease: false

    docker_image:
        needs: [build_version, tag_and_release]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                scope: 'repository'

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: |
                  ghcr.io/${{ github.repository_owner }}/quiz-backend:${{ needs.build_version.outputs.version }}
                  ghcr.io/${{ github.repository_owner }}/quiz-backend:latest
                platforms: linux/amd64,linux/arm64